name: Workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      NODE: '18'
    steps:
    - name: Generate coverage report
      run: |
        npm run test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        #token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./client/coverage/
        #env_vars: OS,PYTHON
        #fail_ci_if_error: true
        #files: ./coverage1.xml,./coverage2.xml,!./cache
        #flags: unittests
        #name: codecov-umbrella
        verbose: true
